"""
Sprint 9a â€” Godot 4 Project Export

Generates a complete, runnable Godot 4 project from a demake manifest.
Phaser remains the live browser player; this is an additional downloadable
artifact per demake.

Architecture doc reference (Sprint 9a):
  manifest -> Godot project folder (project.godot, scenes, GDScript genre
  templates, sprites, tilemap data) -> open in editor -> Play / export.

Approach: the manifest.json ships inside the project and the world is built
at runtime in GDScript (colored-rect tiles + static bodies, mirroring the
Phaser TilemapRenderer), so no TileSet resource authoring is needed.
Genre scripts extend a shared base script â€” same architecture as game.html.

Audio: deferred â€” Godot has no native MIDI playback. Runtime chiptune synth
is a stretch goal, not a blocker.
"""
import os
import json
import shutil
import zipfile

# Windows Godot binary (winget install) â€” used only by the CLI validator,
# never by the web server.
GODOT_CANDIDATES = [
    os.path.expandvars(r"%LOCALAPPDATA%\Microsoft\WinGet\Links\godot.cmd"),
    os.path.expandvars(r"%LOCALAPPDATA%\Programs\Godot\Godot.exe"),
    r"C:\Program Files\Godot\Godot.exe",
]

VALID_GENRES = [
    "wave_shooter",
    "top_down_action_rpg",
    "open_world_sandbox",
    "side_scroll_platformer",
    "turn_based_rpg",
]

# Sprite slot -> (default frame width, frame height, frame count)
SPRITE_SLOTS = {
    "sprite_player":     (16, 16, 8),
    "sprite_enemy":      (16, 16, 4),
    "sprite_boss":       (32, 32, 2),
    "sprite_projectile": (8, 8, 2),
    "tile_floor":        (16, 16, 1),
    "tile_wall":         (16, 16, 1),
}

# â”€â”€ project.godot â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

PROJECT_GODOT_TMPL = """\
; Engine configuration file â€” generated by demake-engine Sprint 9a
config_version=5

[application]

config/name="{title} (Demake)"
run/main_scene="res://scenes/main.tscn"
config/features=PackedStringArray("4.7")

[display]

window/size/viewport_width=480
window/size/viewport_height=320
window/stretch/mode="canvas_items"
window/stretch/aspect="keep"

[rendering]

textures/canvas_textures/default_texture_filter=0
environment/defaults/default_clear_color=Color({clear_color})
"""

MAIN_TSCN = """\
[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://scripts/main.gd" id="1_main"]

[node name="Main" type="Node2D"]
script = ExtResource("1_main")
"""

MAIN_GD_TMPL = """\
# Thin dispatcher â€” generated for the "{genre}" template.
# All real logic lives in the genre script this extends.
extends "res://scripts/genres/{genre}.gd"
"""

# â”€â”€ scripts/base.gd â€” shared systems (mirrors game.html shared code) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

BASE_GD = r"""extends Node2D
# DEMAKE shared systems â€” Sprint 9a.
# Mirrors frontend/game.html: palette normalization, tilemap build
# (colored rects + static bodies), spritesheet frame slicing, spawn points.

const TILE := 16

var manifest: Dictionary = {}
var palette: Dictionary = {}
var world_w := 480.0
var world_h := 320.0
var walls_node: Node2D
var player: CharacterBody2D
var player_speed := 120.0
var hud_layer: CanvasLayer
var hud_labels: Dictionary = {}
var game_over := false
var score := 0


func _ready() -> void:
	manifest = _load_json("res://manifest.json")
	if manifest.is_empty():
		push_error("manifest.json missing or invalid")
		return
	_norm_palette()
	_build_world()
	_build_hud()
	_genre_setup()


func _load_json(path: String) -> Dictionary:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		return {}
	var data = JSON.parse_string(f.get_as_text())
	return data if typeof(data) == TYPE_DICTIONARY else {}


func _col(v, fallback: String) -> Color:
	if typeof(v) == TYPE_STRING and String(v).begins_with("#"):
		return Color(String(v))
	return Color(fallback)


func _norm_palette() -> void:
	var p = manifest.get("palette", {})
	# Manifest palette values are hex strings from the backend.
	palette = {
		"primary":    _col(p.get("primary", "#1a0a00"), "#1a0a00"),
		"secondary":  _col(p.get("secondary", "#3d2b1f"), "#3d2b1f"),
		"accent":     _col(p.get("accent", "#8b1a00"), "#8b1a00"),
		"highlight":  _col(p.get("highlight", "#ff4400"), "#ff4400"),
		"background": _col(p.get("background", "#0d0500"), "#0d0500"),
		"floor":      _col(p.get("floor", p.get("primary", "#1a0e06")), "#1a0e06"),
		"wall":       _col(p.get("wall", p.get("secondary", "#0f0804")), "#0f0804"),
	}


# â”€â”€ World build (mirrors TilemapRenderer) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

func _build_world() -> void:
	var tm = manifest.get("tilemap", {})
	if tm.is_empty() or not tm.has("grid"):
		_build_fallback_arena()
		return

	var grid: Array = tm["grid"]
	var defs = tm.get("tile_defs", {})
	var height: int = grid.size()
	var width: int = (grid[0] as Array).size() if height > 0 else 0
	world_w = width * TILE
	world_h = height * TILE

	var bg := ColorRect.new()
	bg.color = palette["background"]
	bg.position = Vector2.ZERO
	bg.size = Vector2(world_w, world_h)
	bg.z_index = -10
	add_child(bg)

	walls_node = Node2D.new()
	walls_node.name = "Walls"
	add_child(walls_node)

	for y in range(height):
		var row: Array = grid[y]
		for x in range(width):
			var tile_id: String = str(row[x]) if x < row.size() else "void"
			if tile_id == "void" or tile_id == "player":
				continue
			if tile_id == "enemy" or tile_id == "spawn":
				continue
			var def = defs.get(tile_id, {})
			var col: Color = Color(str(def.get("color", "#333333")))
			var passable: bool = bool(def.get("passable", true))
			var px := x * TILE
			var py := y * TILE

			var rect := ColorRect.new()
			rect.color = col
			rect.position = Vector2(px + 1, py + 1)
			rect.size = Vector2(TILE - 1, TILE - 1)
			rect.z_index = 2 if not passable else 1
			add_child(rect)

			if tile_id == "chest" or tile_id == "mission" or tile_id == "goal":
				_add_label("*", Vector2(px + 4, py - 2), Color.YELLOW, 3)
			elif tile_id == "gym":
				var g := ColorRect.new()
				g.color = Color("aa3333")
				g.position = Vector2(px + 1, py + 1)
				g.size = Vector2(TILE - 2, TILE - 2)
				g.z_index = 3
				add_child(g)
				_add_label("G", Vector2(px + 4, py - 2), Color(1, 0.87, 0.87), 4)

			if not passable:
				var body := StaticBody2D.new()
				body.position = Vector2(px + TILE / 2.0, py + TILE / 2.0)
				var shape := CollisionShape2D.new()
				var rshape := RectangleShape2D.new()
				rshape.size = Vector2(TILE, TILE)
				shape.shape = rshape
				body.add_child(shape)
				walls_node.add_child(body)

	# Spawn points
	var sp = tm.get("spawn_points", {})
	var psp = sp.get("player", [2, int(height / 2.0)])
	player_spawn_px = Vector2(psp[0] * TILE + TILE / 2.0, psp[1] * TILE + TILE / 2.0)
	for e in sp.get("enemies", []):
		enemy_spawn_px.append(Vector2(e[0] * TILE + TILE / 2.0, e[1] * TILE + TILE / 2.0))
	for i in sp.get("items", []):
		item_spawn_px.append({
			"pos": Vector2(i[0] * TILE + TILE / 2.0, i[1] * TILE + TILE / 2.0),
			"tile": str(grid[i[1]][i[0]]) if i[1] < grid.size() and i[0] < (grid[i[1]] as Array).size() else "item",
		})


var player_spawn_px := Vector2(60, 160)
var enemy_spawn_px: Array[Vector2] = []
var item_spawn_px: Array[Dictionary] = []


func _build_fallback_arena() -> void:
	world_w = 480
	world_h = 320
	var bg := ColorRect.new()
	bg.color = palette["background"]
	bg.size = Vector2(world_w, world_h)
	bg.z_index = -10
	add_child(bg)
	walls_node = Node2D.new()
	add_child(walls_node)
	_add_wall_strip(Vector2(0, 0), Vector2(world_w, 16))
	_add_wall_strip(Vector2(0, world_h - 16), Vector2(world_w, 16))
	_add_wall_strip(Vector2(0, 0), Vector2(16, world_h))
	_add_wall_strip(Vector2(world_w - 16, 0), Vector2(16, world_h))
	player_spawn_px = Vector2(world_w / 4.0, world_h / 2.0)
	enemy_spawn_px = [
		Vector2(world_w * 0.75, world_h / 2.0),
		Vector2(world_w / 2.0, world_h / 4.0),
		Vector2(world_w / 2.0, world_h * 0.75),
	]


func _add_wall_strip(pos: Vector2, size: Vector2) -> void:
	var rect := ColorRect.new()
	rect.color = palette["wall"]
	rect.position = pos
	rect.size = size
	rect.z_index = 2
	add_child(rect)
	var body := StaticBody2D.new()
	body.position = pos + size / 2.0
	var shape := CollisionShape2D.new()
	var rshape := RectangleShape2D.new()
	rshape.size = size
	shape.shape = rshape
	body.add_child(shape)
	walls_node.add_child(body)


func _add_label(text: String, pos: Vector2, color: Color, z: int) -> void:
	var l := Label.new()
	l.text = text
	l.position = pos
	l.add_theme_font_size_override("font_size", 10)
	l.add_theme_color_override("font_color", color)
	l.z_index = z
	add_child(l)


# â”€â”€ Actors â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

func make_actor(pos: Vector2, sprite_slot: String, fallback_color: Color,
		scale_f := 1.0) -> CharacterBody2D:
	var body := CharacterBody2D.new()
	body.position = pos
	body.collision_layer = 1
	var shape := CollisionShape2D.new()
	var rshape := RectangleShape2D.new()
	rshape.size = Vector2(12, 12) * scale_f
	shape.shape = rshape
	body.add_child(shape)

	var tex := _slot_frame_texture(sprite_slot, 0)
	if tex != null:
		var spr := Sprite2D.new()
		spr.texture = tex
		spr.scale = Vector2(scale_f, scale_f)
		body.add_child(spr)
		body.set_meta("slot", sprite_slot)
		body.set_meta("frame", 0)
		body.set_meta("anim_ms", 0.0)
	else:
		var rect := ColorRect.new()
		rect.color = fallback_color
		rect.position = Vector2(-6 * scale_f, -6 * scale_f)
		rect.size = Vector2(12 * scale_f, 12 * scale_f)
		body.add_child(rect)
	add_child(body)
	return body


func _slot_texture(slot: String) -> Texture2D:
	var sprites = manifest.get("assets", {}).get("sprites", {})
	var url = sprites.get(slot, "")
	if typeof(url) == TYPE_STRING and url.begins_with("res://"):
		var tex = load(url)
		if tex != null:
			return tex
	return null


# Spritesheets are horizontal strips â€” slice single frames via AtlasTexture
# (frame width from manifest sprite_meta, with sane fallbacks).
const SLOT_FRAME_W := {
	"sprite_player": 16, "sprite_enemy": 16, "sprite_boss": 32,
	"sprite_projectile": 8, "tile_floor": 16, "tile_wall": 16,
}


func _slot_frame_texture(slot: String, frame: int) -> Texture2D:
	var tex := _slot_texture(slot)
	if tex == null:
		return null
	var fw := int(SLOT_FRAME_W.get(slot, 16))
	var meta = manifest.get("assets", {}).get("sprite_meta", {}).get(slot.replace("sprite_", ""), {})
	if typeof(meta) == TYPE_DICTIONARY and meta.has("frame_width"):
		fw = int(meta["frame_width"])
	var count := int(tex.get_width() / fw)
	if count < 1:
		count = 1
	frame = absi(frame) % count
	var at := AtlasTexture.new()
	at.atlas = tex
	at.region = Rect2(frame * fw, 0, fw, tex.get_height())
	return at


# Simple frame-cycler for actors carrying slot meta (player + enemies)
func _animate_actors(delta: float) -> void:
	for e in get_tree().get_nodes_in_group("enemies"):
		_cycle_frames(e, delta, 6.0)
	if player != null and is_instance_valid(player):
		var moving: bool = player.velocity.length() > 5.0
		_cycle_frames(player, delta, 8.0 if moving else 3.0)


func _cycle_frames(body: Node2D, delta: float, fps: float) -> void:
	if not is_instance_valid(body) or not body.has_meta("slot"):
		return
	var t := float(body.get_meta("anim_ms")) + delta * 1000.0
	body.set_meta("anim_ms", t)
	if t < 1000.0 / fps:
		return
	body.set_meta("anim_ms", 0.0)
	var f := int(body.get_meta("frame")) + 1
	body.set_meta("frame", f)
	for c in body.get_children():
		if c is Sprite2D:
			var tex := _slot_frame_texture(String(body.get_meta("slot")), f)
			if tex != null:
				c.texture = tex
			break


func add_enemy(pos: Vector2, hp: int, speed: float, damage: float,
		is_boss := false) -> CharacterBody2D:
	var slot := "sprite_boss" if is_boss else "sprite_enemy"
	var scale_f := 2.0 if is_boss else 1.0
	var e := make_actor(pos, slot, Color("4a6b2a"), scale_f)
	e.add_to_group("enemies")
	e.set_meta("hp", hp)
	e.set_meta("max_hp", hp)
	e.set_meta("speed", speed)
	e.set_meta("damage", damage)
	e.set_meta("is_boss", is_boss)
	e.set_meta("last_hit_ms", 0.0)
	return e


func move_toward_player(e: CharacterBody2D, delta: float) -> void:
	if player == null or not is_instance_valid(player):
		return
	var dir := (player.global_position - e.global_position).normalized()
	e.velocity = dir * float(e.get_meta("speed"))
	e.move_and_slide()


func enemies_alive() -> int:
	return get_tree().get_nodes_in_group("enemies").size()


func damage_enemy(e: CharacterBody2D, amount: int) -> bool:
	var hp := int(e.get_meta("hp")) - amount
	e.set_meta("hp", hp)
	# red flash
	e.modulate = Color(1, 0.2, 0.2)
	var tw := create_tween()
	tw.tween_property(e, "modulate", Color.WHITE, 0.12)
	return hp <= 0


# â”€â”€ Projectiles â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

func fire_bullet(pos: Vector2, angle: float, speed: float, damage: int,
		target_group: String, color := Color(1.0, 0.8, 0.0)) -> Area2D:
	var b := Area2D.new()
	b.position = pos
	b.collision_layer = 0
	b.collision_mask = 1
	b.set_meta("damage", damage)
	b.set_meta("target_group", target_group)
	b.set_meta("born_ms", _now_ms())

	var shape := CollisionShape2D.new()
	var rshape := RectangleShape2D.new()
	rshape.size = Vector2(6, 4)
	shape.shape = rshape
	b.add_child(shape)

	var spr := Sprite2D.new()
	var tex = _slot_frame_texture("sprite_projectile", 0)
	if tex != null:
		spr.texture = tex
	else:
		spr = null
	if spr != null:
		b.add_child(spr)
	else:
		var rect := ColorRect.new()
		rect.color = color
		rect.position = Vector2(-3, -2)
		rect.size = Vector2(6, 4)
		b.add_child(rect)
	add_child(b)

	var dir := Vector2.RIGHT.rotated(angle)
	b.set_meta("dir", dir)
	b.body_entered.connect(_on_bullet_body_entered.bind(b))
	_bullets.append(b)
	return b


var _bullets: Array[Area2D] = []

func _process_bullets(delta: float) -> void:
	for b in _bullets.duplicate():
		if not is_instance_valid(b):
			_bullets.erase(b)
			continue
		var dir: Vector2 = b.get_meta("dir")
		b.position += dir * 380.0 * delta
		# lifetime + bounds
		if _now_ms() - float(b.get_meta("born_ms")) > 2500.0 \
				or b.position.x < 0 or b.position.x > world_w \
				or b.position.y < 0 or b.position.y > world_h:
			b.queue_free()
			_bullets.erase(b)


func _on_bullet_body_entered(body: Node, b: Area2D) -> void:
	_bullet_hit(b, body)


func _bullet_hit(b: Area2D, other: Node) -> void:
	if other.is_in_group(String(b.get_meta("target_group"))):
		_on_bullet_hit_target(b, other)
		if is_instance_valid(b):
			b.queue_free()
			_bullets.erase(b)
	elif other is StaticBody2D:
		b.queue_free()
		_bullets.erase(b)


# Genre scripts override this
func _on_bullet_hit_target(_b: Area2D, _target: Node) -> void:
	pass


# â”€â”€ HUD â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

func _build_hud() -> void:
	hud_layer = CanvasLayer.new()
	add_child(hud_layer)
	var bar := ColorRect.new()
	bar.color = Color(0, 0, 0, 0.75)
	bar.position = Vector2.ZERO
	bar.size = Vector2(480, 24)
	hud_layer.add_child(bar)


func hud_text(key: String, pos: Vector2, initial: String) -> Label:
	var l := Label.new()
	l.text = initial
	l.position = pos
	l.add_theme_font_size_override("font_size", 10)
	hud_layer.add_child(l)
	hud_labels[key] = l
	return l


func hud_set(key: String, text: String) -> void:
	if hud_labels.has(key):
		hud_labels[key].text = text


func _now_ms() -> float:
	return Time.get_ticks_msec()


func show_center_message(msg: String, color := Color.WHITE) -> void:
	var l := Label.new()
	l.text = msg
	l.position = Vector2(240 - msg.length() * 3.0, 150)
	l.add_theme_font_size_override("font_size", 16)
	l.add_theme_color_override("font_color", color)
	hud_layer.add_child(l)


func trigger_game_over(msg: String, color: Color) -> void:
	if game_over:
		return
	game_over = true
	var dim := ColorRect.new()
	dim.color = Color(0, 0, 0, 0.7)
	dim.size = Vector2(480, 320)
	hud_layer.add_child(dim)
	var l := Label.new()
	l.text = msg
	l.position = Vector2(240 - msg.length() * 4.0, 140)
	l.add_theme_font_size_override("font_size", 20)
	l.add_theme_color_override("font_color", color)
	hud_layer.add_child(l)


# â”€â”€ Genre hooks â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

func _genre_setup() -> void:
	pass


func _genre_update(_delta: float) -> void:
	pass
"""

# â”€â”€ Genre scripts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

GENRE_WAVE_SHOOTER = r"""extends "res://scripts/base.gd"
# Wave Shooter template â€” mirrors GameScene in game.html.

var wave_num := 1
var ammo := 30
var max_ammo := 30
var reloading := false
var last_fired_ms := 0.0
var enemies_left := 0
var hp := 100
var max_hp := 100
var _spawn_timer := 0.0
var _spawn_queue := 0
var _next_wave_timer := 0.0


func _genre_setup() -> void:
	var cfg = manifest.get("game_config", {})
	var pcfg = cfg.get("player", {})
	var wcfg = cfg.get("waves", {})
	max_ammo = int(pcfg.get("max_ammo", 30))
	ammo = max_ammo
	max_hp = int(pcfg.get("max_hp", 100))
	hp = max_hp
	player_speed = float(cfg.get("physics", {}).get("player_speed", 130))

	player = make_actor(player_spawn_px, "sprite_player", Color("4a6b3a"))
	player.add_to_group("player")

	hud_text("hp", Vector2(8, 6), "HP %d/%d" % [hp, max_hp])
	hud_text("ammo", Vector2(200, 6), "AMMO %d/%d" % [ammo, max_ammo])
	hud_text("wave", Vector2(360, 6), "WAVE 1")
	_start_wave()


func _start_wave() -> void:
	var wcfg = manifest.get("game_config", {}).get("waves", {})
	var boss_every := int(wcfg.get("boss_every", 5))
	var count := int(float(wcfg.get("start_count", 6)) * pow(float(wcfg.get("multiplier", 1.4)), wave_num - 1))
	enemies_left = count + (1 if wave_num % boss_every == 0 else 0)
	_spawn_queue = count
	hud_set("wave", "WAVE %d%s" % [wave_num, " (BOSS!)" if wave_num % boss_every == 0 else ""])


func _spawn_enemy(is_boss: bool) -> void:
	var cfg = manifest.get("game_config", {})
	var ecfg = cfg.get("enemy", {})
	var bcfg = cfg.get("boss", {})
	var pos: Vector2
	if enemy_spawn_px.size() > 0:
		pos = enemy_spawn_px[randi() % enemy_spawn_px.size()]
	else:
		pos = Vector2(randf_range(32, world_w - 32), randf_range(32, world_h - 32))

	var hp_i: int
	var spd: float
	var dmg: float
	if is_boss:
		hp_i = int(float(ecfg.get("base_hp", 30)) * float(bcfg.get("hp_mult", 8)) * pow(float(ecfg.get("hp_scale", 1.2)), wave_num))
		spd = float(ecfg.get("base_speed", 55)) * float(bcfg.get("speed_mult", 0.6))
		dmg = float(ecfg.get("damage", 10)) * float(bcfg.get("damage_mult", 3))
	else:
		hp_i = int(float(ecfg.get("base_hp", 30)) * pow(float(ecfg.get("hp_scale", 1.2)), wave_num - 1))
		spd = float(ecfg.get("base_speed", 55)) * pow(float(ecfg.get("speed_scale", 1.05)), wave_num - 1)
		dmg = float(ecfg.get("damage", 10))
	add_enemy(pos, hp_i, spd, dmg, is_boss)


func _process(delta: float) -> void:
	if game_over:
		return
	_genre_update(delta)


func _genre_update(delta: float) -> void:
	# Movement
	var dir := Vector2.ZERO
	if Input.is_physical_key_pressed(KEY_A) or Input.is_physical_key_pressed(KEY_LEFT):
		dir.x -= 1
	if Input.is_physical_key_pressed(KEY_D) or Input.is_physical_key_pressed(KEY_RIGHT):
		dir.x += 1
	if Input.is_physical_key_pressed(KEY_W) or Input.is_physical_key_pressed(KEY_UP):
		dir.y -= 1
	if Input.is_physical_key_pressed(KEY_S) or Input.is_physical_key_pressed(KEY_DOWN):
		dir.y += 1
	player.velocity = dir.normalized() * player_speed
	player.move_and_slide()

	# Shooting â€” mouse aim, hold left button
	if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
		_try_shoot()

	if Input.is_physical_key_pressed(KEY_R):
		_start_reload()

	# Spawning trickle
	if _spawn_queue > 0:
		_spawn_timer -= delta
		if _spawn_timer <= 0.0:
			_spawn_timer = float(manifest.get("game_config", {}).get("waves", {}).get("spawn_delay_ms", 700)) / 1000.0
			_spawn_queue -= 1
			var boss_every := int(manifest.get("game_config", {}).get("waves", {}).get("boss_every", 5))
			_spawn_enemy(_spawn_queue == 0 and wave_num % boss_every == 0)

	# Wave clear
	if enemies_alive() == 0 and _spawn_queue <= 0:
		_next_wave_timer -= delta
		if _next_wave_timer <= 0.0:
			wave_num += 1
			_next_wave_timer = 2.5
			_start_wave()
	else:
		_next_wave_timer = 2.5

	# Enemy AI + touch damage
	for e in get_tree().get_nodes_in_group("enemies"):
		if not is_instance_valid(e):
			continue
		move_toward_player(e, delta)
		if player.global_position.distance_to(e.global_position) < 14.0:
			var now := _now_ms()
			if now - float(e.get_meta("last_hit_ms")) > 600.0:
				e.set_meta("last_hit_ms", now)
				hp -= int(e.get_meta("damage"))
				hud_set("hp", "HP %d/%d" % [max(hp, 0), max_hp])
				if hp <= 0:
					trigger_game_over("YOU DIED â€” WAVE %d" % wave_num, Color.RED)

	_animate_actors(delta)
	_process_bullets(delta)


func _try_shoot() -> void:
	var pcfg = manifest.get("game_config", {}).get("player", {})
	var now := _now_ms()
	if reloading:
		return
	if ammo <= 0:
		_start_reload()
		return
	if now - last_fired_ms < float(pcfg.get("fire_rate_ms", 150)):
		return
	last_fired_ms = now
	ammo -= 1
	hud_set("ammo", "AMMO %d/%d" % [ammo, max_ammo])
	var angle := (get_global_mouse_position() - player.global_position).angle()
	fire_bullet(player.global_position, angle,
		float(manifest.get("game_config", {}).get("physics", {}).get("bullet_speed", 380)),
		25, "enemies")
	if ammo == 0:
		_start_reload()


func _start_reload() -> void:
	if reloading:
		return
	reloading = true
	hud_set("ammo", "RELOADING...")
	var timer := get_tree().create_timer(float(manifest.get("game_config", {}).get("player", {}).get("reload_time_ms", 1800)) / 1000.0)
	timer.timeout.connect(func():
		ammo = max_ammo
		reloading = false
		hud_set("ammo", "AMMO %d/%d" % [ammo, max_ammo]))


func _on_bullet_hit_target(b: Area2D, target: Node) -> void:
	if damage_enemy(target, int(b.get_meta("damage"))):
		var was_boss: bool = target.get_meta("is_boss")
		target.queue_free()
		score += 500 if was_boss else 50
		enemies_left -= 1
"""

GENRE_TOP_DOWN_RPG = r"""extends "res://scripts/base.gd"
# Top-Down Action RPG â€” mirrors TopDownRPGScene in game.html.
# Includes the Sprint 9a final-room boss: the spawn farthest from the player
# becomes a scaled-up boss; the room is clear only when everything dies.

var hp := 120
var max_hp := 120
var mp := 60
var max_mp := 60
var attack_dmg := 25
var attack_range := 50.0
var magic_dmg := 30
var _attack_cd := 0.0
var _magic_cd := 0.0
var potions := 0
var boss: CharacterBody2D = null


func _genre_setup() -> void:
	var cfg = manifest.get("game_config", {})
	var ccfg = cfg.get("combat", {})
	max_hp = int(ccfg.get("max_hp", 120))
	hp = max_hp
	max_mp = int(ccfg.get("max_mp", 60))
	mp = max_mp
	attack_dmg = int(ccfg.get("attack_damage", 25))
	attack_range = float(ccfg.get("attack_range", 50))
	magic_dmg = int(ccfg.get("base_magic", 30))
	player_speed = float(cfg.get("physics", {}).get("player_speed", 110))

	player = make_actor(player_spawn_px, "sprite_player", Color("4a6b3a"), 1.5)
	player.add_to_group("player")

	# Enemies â€” the spawn farthest from the player is the boss (Sprint 9a / 8C)
	var ecfg = cfg.get("enemy", {})
	var base_hp := int(ecfg.get("base_hp", 50))
	var spd := float(ecfg.get("base_speed", 45))
	var farthest := Vector2.ZERO
	var far_d := -1.0
	if enemy_spawn_px.size() == 0:
		enemy_spawn_px = [Vector2(80, 80), Vector2(world_w - 80, 80),
			Vector2(80, world_h - 80), Vector2(world_w - 80, world_h - 80)]
	for pos in enemy_spawn_px:
		var d := player_spawn_px.distance_to(pos)
		if d > far_d:
			far_d = d
			farthest = pos
	for pos in enemy_spawn_px:
		if pos == farthest:
			boss = add_enemy(pos, base_hp * 6, spd * 0.8, float(ecfg.get("damage", 15)) * 2.0, true)
		else:
			add_enemy(pos, base_hp, spd, float(ecfg.get("damage", 15)))

	# Chests from item spawns
	for item in item_spawn_px:
		if String(item.get("tile", "")) == "chest":
			var c := Area2D.new()
			c.position = item["pos"]
			c.set_meta("chest", true)
			var shape := CollisionShape2D.new()
			var rshape := RectangleShape2D.new()
			rshape.size = Vector2(20, 20)
			shape.shape = rshape
			c.add_child(shape)
			var rect := ColorRect.new()
			rect.color = Color("8b4513")
			rect.position = Vector2(-7, -5)
			rect.size = Vector2(14, 10)
			c.add_child(rect)
			add_child(c)

	hud_text("hp", Vector2(8, 6), "HP %d/%d" % [hp, max_hp])
	hud_text("mp", Vector2(120, 6), "MP %d/%d" % [mp, max_mp])
	hud_text("pot", Vector2(230, 6), "")
	hud_text("score", Vector2(380, 6), "SCORE 0")
	if boss != null:
		show_center_message("THE BOSS AWAITS...", Color(1, 0.4, 0.3))


func _process(delta: float) -> void:
	if game_over:
		return
	_genre_update(delta)


func _genre_update(delta: float) -> void:
	var dir := Vector2.ZERO
	if Input.is_physical_key_pressed(KEY_A):
		dir.x -= 1
	if Input.is_physical_key_pressed(KEY_D):
		dir.x += 1
	if Input.is_physical_key_pressed(KEY_W):
		dir.y -= 1
	if Input.is_physical_key_pressed(KEY_S):
		dir.y += 1
	player.velocity = dir.normalized() * player_speed
	player.move_and_slide()

	_attack_cd -= delta
	_magic_cd -= delta

	if Input.is_physical_key_pressed(KEY_SPACE) and _attack_cd <= 0.0:
		_attack_cd = 0.4
		_melee()
	if Input.is_physical_key_pressed(KEY_E) and _magic_cd <= 0.0 and mp >= 10:
		_magic_cd = 0.5
		_magic()
	if Input.is_physical_key_pressed(KEY_Q) and potions > 0 and hp < max_hp:
		potions -= 1
		hp = min(max_hp, hp + int(max_hp * 0.4))
		hud_set("pot", "POTION x%d (Q)" % potions if potions > 0 else "")
		hud_set("hp", "HP %d/%d" % [hp, max_hp])

	# Enemy AI + touch damage
	var dmg := float(manifest.get("game_config", {}).get("enemy", {}).get("damage", 15))
	for e in get_tree().get_nodes_in_group("enemies"):
		if not is_instance_valid(e):
			continue
		move_toward_player(e, delta)
		if player.global_position.distance_to(e.global_position) < 14.0:
			var now := _now_ms()
			if now - float(e.get_meta("last_hit_ms")) > 800.0:
				e.set_meta("last_hit_ms", now)
				hp -= int(dmg)
				hud_set("hp", "HP %d/%d" % [max(hp, 0), max_hp])
				if hp <= 0:
					trigger_game_over("YOU DIED", Color.RED)

	_animate_actors(delta)
	_process_bullets(delta)

	# Win â€” everything dead, boss included
	if enemies_alive() == 0 and boss != null:
		trigger_game_over("ROOM CLEAR! +500", Color(0.3, 1.0, 0.3))
		score += 500


func _nearest_enemy() -> Node:
	var best: Node = null
	var best_d := INF
	for e in get_tree().get_nodes_in_group("enemies"):
		var d: float = player.global_position.distance_to(e.global_position)
		if d < best_d:
			best_d = d
			best = e
	return best


func _melee() -> void:
	for e in get_tree().get_nodes_in_group("enemies"):
		if player.global_position.distance_to(e.global_position) < attack_range:
			if damage_enemy(e, attack_dmg):
				_kill_enemy(e, 100)


func _magic() -> void:
	mp -= 10
	hud_set("mp", "MP %d/%d" % [mp, max_mp])
	var target := _nearest_enemy()
	var angle := 0.0
	if target != null:
		angle = (target.global_position - player.global_position).angle()
	fire_bullet(player.global_position, angle, 260.0, magic_dmg, "enemies", Color(0.67, 0.4, 1.0))


func _on_bullet_hit_target(b: Area2D, target: Node) -> void:
	if damage_enemy(target, int(b.get_meta("damage"))):
		_kill_enemy(target, 150)


func _kill_enemy(e: Node, points: int) -> void:
	var was_boss: bool = e.get_meta("is_boss")
	e.queue_free()
	score += points
	hud_set("score", "SCORE %d" % score)
	if was_boss:
		show_center_message("BOSS DOWN!", Color(1, 0.85, 0.2))
"""

GENRE_OPEN_WORLD = r"""extends "res://scripts/base.gd"
# Open World Sandbox â€” mirrors OpenWorldScene in game.html (core loop).

var hp := 100
var cash := 0
var wanted := 0
var max_wanted := 5
var _last_crime_ms := 0.0
var npcs: Array[CharacterBody2D] = []
var police: Array[CharacterBody2D] = []
var mission_pos := Vector2.ZERO
var mission_marker: ColorRect = null


func _genre_setup() -> void:
	player_speed = float(manifest.get("game_config", {}).get("physics", {}).get("player_speed", 100))
	player = make_actor(player_spawn_px, "sprite_player", Color("4a6b3a"), 1.5)
	player.add_to_group("player")

	var count := 8 if enemy_spawn_px.size() == 0 else enemy_spawn_px.size()
	for i in range(count):
		var pos: Vector2 = enemy_spawn_px[i] if i < enemy_spawn_px.size() \
			else Vector2(randf_range(40, world_w - 40), randf_range(40, world_h - 40))
		var npc := make_actor(pos, "sprite_enemy", Color("4a6b2a"), 0.9)
		npc.add_to_group("npcs")
		npc.set_meta("wander_angle", randf() * TAU)
		npc.set_meta("wander_timer", 0.0)
		npcs.append(npc)

	mission_pos = Vector2(world_w * 0.75, world_h * 0.25)
	mission_marker = ColorRect.new()
	mission_marker.color = Color.YELLOW
	mission_marker.position = mission_pos - Vector2(3, 3)
	mission_marker.size = Vector2(6, 6)
	mission_marker.z_index = 8
	add_child(mission_marker)

	hud_text("hp", Vector2(8, 6), "HP %d" % hp)
	hud_text("cash", Vector2(200, 6), "$0")
	hud_text("wanted", Vector2(360, 6), "* * * * *")


func _process(delta: float) -> void:
	if game_over:
		return
	_genre_update(delta)


func _genre_update(delta: float) -> void:
	var dir := Vector2.ZERO
	if Input.is_physical_key_pressed(KEY_A):
		dir.x -= 1
	if Input.is_physical_key_pressed(KEY_D):
		dir.x += 1
	if Input.is_physical_key_pressed(KEY_W):
		dir.y -= 1
	if Input.is_physical_key_pressed(KEY_S):
		dir.y += 1
	if dir.x != 0:
		pass  # facing handled via last dir
	player.velocity = dir.normalized() * player_speed
	player.move_and_slide()
	if dir.x != 0:
		player.set_meta("facing", signf(dir.x))

	if Input.is_physical_key_pressed(KEY_SPACE):
		_shoot()

	# Civilians wander
	for npc in npcs:
		if not is_instance_valid(npc):
			continue
		var t := float(npc.get_meta("wander_timer")) - delta * 1000.0
		if t <= 0.0:
			npc.set_meta("wander_angle", float(npc.get_meta("wander_angle")) + randf_range(-0.75, 0.75))
			t = 1000.0
		npc.set_meta("wander_timer", t)
		var a := float(npc.get_meta("wander_angle"))
		npc.velocity = Vector2(cos(a), sin(a)) * 25.0
		npc.move_and_slide()

	# Police chase
	for cop in police:
		if not is_instance_valid(cop):
			continue
		move_toward_player(cop, delta)
		if player.global_position.distance_to(cop.global_position) < 14.0:
			hp -= 6 + wanted * 3
			hud_set("hp", "HP %d" % max(hp, 0))
			if hp <= 0:
				trigger_game_over("WASTED!", Color.RED)

	# Wanted decay â€” 1 star / 20s
	if wanted > 0 and _now_ms() - _last_crime_ms > 20000.0:
		_set_wanted(wanted - 1)

	# Mission
	if player.global_position.distance_to(mission_pos) < 30.0:
		cash += 500
		hud_set("cash", "$%d" % cash)
		mission_pos = Vector2(randf_range(100, world_w - 100), randf_range(100, world_h - 100))
		mission_marker.position = mission_pos - Vector2(3, 3)

	# Busted â€” 3+ stars, 2+ cops in range
	if wanted >= 3:
		var grabbing := 0
		for cop in police:
			if is_instance_valid(cop) and player.global_position.distance_to(cop.global_position) < 30.0:
				grabbing += 1
		if grabbing >= 2:
			cash /= 2
			hud_set("cash", "$%d" % cash)
			_set_wanted(0)
			player.position = player_spawn_px
			show_center_message("BUSTED! LOST HALF CASH", Color(0.3, 0.5, 1.0))

	_animate_actors(delta)
	_process_bullets(delta)


func _shoot() -> void:
	var now := _now_ms()
	if now - float(player.get_meta("last_shot_ms") if player.has_meta("last_shot_ms") else 0.0) < 250.0:
		return
	player.set_meta("last_shot_ms", now)
	var facing := float(player.get_meta("facing") if player.has_meta("facing") else 1.0)
	var angle := 0.0 if facing >= 0 else PI
	fire_bullet(player.global_position, angle, 320.0, 34, "npcs")


func _set_wanted(n: int) -> void:
	wanted = clampi(n, 0, max_wanted)
	_last_crime_ms = _now_ms()
	hud_set("wanted", "*".repeat(wanted) + ".".repeat(max_wanted - wanted))
	while police.size() < wanted:
		var edge := randi() % 4
		var pos := Vector2.ZERO
		match edge:
			0: pos = Vector2(20, randf_range(40, world_h - 40))
			1: pos = Vector2(world_w - 20, randf_range(40, world_h - 40))
			2: pos = Vector2(randf_range(40, world_w - 40), 20)
			3: pos = Vector2(randf_range(40, world_w - 40), world_h - 20)
		var cop := make_actor(pos, "sprite_enemy", Color(0.3, 0.5, 1.0), 0.9)
		cop.add_to_group("police")
		cop.set_meta("speed", 55.0 + wanted * 15.0)
		cop.set_meta("hp", 30 + wanted * 10)
		cop.set_meta("damage", 6.0 + wanted * 3.0)
		police.append(cop)
	if wanted == 0:
		for cop in police:
			if is_instance_valid(cop):
				cop.queue_free()
		police.clear()


func _on_bullet_hit_target(b: Area2D, target: Node) -> void:
	if target.is_in_group("npcs"):
		target.queue_free()
		npcs.erase(target)
		_set_wanted(wanted + 1)
	elif target.is_in_group("police"):
		var hp_i := int(target.get_meta("hp")) - int(b.get_meta("damage"))
		target.set_meta("hp", hp_i)
		if hp_i <= 0:
			target.queue_free()
			police.erase(target)
			_set_wanted(wanted + 1)
"""

GENRE_PLATFORMER = r"""extends "res://scripts/base.gd"
# Side-Scroll Platformer â€” mirrors PlatformerScene in game.html (core loop).

var lives := 3
var gravity := 800.0
var jump_velocity := -420.0
var coins: Array[ColorRect] = []
var goal_x := -1.0
var invincible_ms := 0.0


func _genre_setup() -> void:
	var cfg = manifest.get("game_config", {})
	gravity = float(cfg.get("physics", {}).get("gravity", 800))
	jump_velocity = float(cfg.get("physics", {}).get("jump_velocity", -420))
	player_speed = float(cfg.get("physics", {}).get("player_speed", 160))
	lives = int(cfg.get("player", {}).get("lives", 3))

	player = make_actor(player_spawn_px, "sprite_player", Color(1.0, 0.3, 0.0), 2.0)
	player.add_to_group("player")

	# Coins + goal from item spawns
	for item in item_spawn_px:
		var pos: Vector2 = item["pos"]
		if String(item.get("tile", "")) == "goal":
			goal_x = pos.x
			var flag := ColorRect.new()
			flag.color = Color.YELLOW
			flag.position = pos + Vector2(2, -20)
			flag.size = Vector2(12, 8)
			flag.z_index = 5
			add_child(flag)
		else:
			var coin := ColorRect.new()
			coin.color = palette["highlight"]
			coin.position = pos - Vector2(2.5, 2.5)
			coin.size = Vector2(5, 5)
			coin.z_index = 4
			add_child(coin)
			coins.append(coin)

	# Enemies patrol
	var spd := float(manifest.get("game_config", {}).get("enemy", {}).get("base_speed", 40))
	for pos in enemy_spawn_px:
		var e := make_actor(pos + Vector2(0, -8), "sprite_enemy", palette["accent"], 1.0)
		e.add_to_group("enemies")
		e.set_meta("hp", 1)
		e.set_meta("speed", spd)
		e.set_meta("damage", 1)
		e.set_meta("dir", -1.0)

	hud_text("lives", Vector2(8, 6), "LIVES %d" % lives)
	hud_text("score", Vector2(220, 6), "SCORE 0")

	var cam := Camera2D.new()
	cam.zoom = Vector2(1.5, 1.5)
	cam.limit_left = 0
	cam.limit_top = 0
	cam.limit_right = int(world_w)
	cam.limit_bottom = int(world_h)
	player.add_child(cam)


func _physics_process(delta: float) -> void:
	if game_over:
		return
	player.velocity.y += gravity * delta
	var dir := 0.0
	if Input.is_physical_key_pressed(KEY_A) or Input.is_physical_key_pressed(KEY_LEFT):
		dir -= 1
	if Input.is_physical_key_pressed(KEY_D) or Input.is_physical_key_pressed(KEY_RIGHT):
		dir += 1
	player.velocity.x = dir * player_speed
	if (Input.is_physical_key_pressed(KEY_W) or Input.is_physical_key_pressed(KEY_SPACE) \
			or Input.is_physical_key_pressed(KEY_UP)) and player.is_on_floor():
		player.velocity.y = jump_velocity
	player.move_and_slide()
	_animate_actors(delta)

	# Enemy patrol + stomp
	for e in get_tree().get_nodes_in_group("enemies"):
		if not is_instance_valid(e):
			continue
		e.velocity.x = float(e.get_meta("dir")) * float(e.get_meta("speed"))
		e.move_and_slide()
		if e.is_on_wall():
			e.set_meta("dir", -float(e.get_meta("dir")))
		if player.global_position.distance_to(e.global_position) < 14.0:
			if player.velocity.y > 0 and player.global_position.y < e.global_position.y - 4:
				e.queue_free()
				score += 100
				hud_set("score", "SCORE %d" % score)
				player.velocity.y = -250
			elif _now_ms() > invincible_ms:
				invincible_ms = _now_ms() + 1500
				lives -= 1
				hud_set("lives", "LIVES %d" % max(lives, 0))
				if lives <= 0:
					trigger_game_over("GAME OVER", Color.RED)

	# Coins
	for coin in coins.duplicate():
		if is_instance_valid(coin) and player.global_position.distance_to(coin.position + coin.size / 2.0) < 12.0:
			coin.queue_free()
			coins.erase(coin)
			score += 10
			hud_set("score", "SCORE %d" % score)

	# Goal
	if goal_x > 0 and player.global_position.x >= goal_x - 12:
		trigger_game_over("LEVEL CLEAR! +%d" % (score + 500), Color(0.3, 1.0, 0.3))
"""

GENRE_TURN_BASED = r"""extends "res://scripts/base.gd"
# Turn-Based RPG â€” mirrors TurnOverworldScene + TurnBasedScene (core loop).
# Overworld: walk, tall grass random encounters, gym tile = boss.
# Battle: simple menu ATTACK / MAGIC / HEAL / RUN.

var player_hp := 80
var player_mp := 40
var max_hp := 80
var max_mp := 40
var in_battle := false
var is_boss_fight := false
var enemy_hp := 60
var enemy_max_hp := 60
var encounters := 0
var _encounter_cd_ms := 0.0
var battle_menu: Array[Label] = []
var selected := 0
var menu_actions := ["ATTACK", "MAGIC", "HEAL", "RUN"]
var battle_log: Label = null
var _enemy_timer := 0.0
var _pending_enemy := false


func _genre_setup() -> void:
	player_speed = float(manifest.get("game_config", {}).get("physics", {}).get("player_speed", 90))
	var bcfg = manifest.get("game_config", {}).get("battle", {})
	max_hp = int(bcfg.get("player_hp", 80))
	player_hp = max_hp
	max_mp = int(bcfg.get("player_mp", 40))
	player_mp = max_mp

	player = make_actor(player_spawn_px, "sprite_player", Color("4a6b3a"), 1.2)
	player.add_to_group("player")

	var cam := Camera2D.new()
	cam.zoom = Vector2(1.5, 1.5)
	cam.limit_left = 0
	cam.limit_top = 0
	cam.limit_right = int(world_w)
	cam.limit_bottom = int(world_h)
	player.add_child(cam)

	hud_text("hp", Vector2(8, 6), "HP %d/%d" % [player_hp, max_hp])
	hud_text("enc", Vector2(360, 6), "GYM AWAITS")


func _process(delta: float) -> void:
	if game_over:
		return
	if in_battle:
		_battle_update(delta)
		return
	_genre_update(delta)


func _genre_update(delta: float) -> void:
	var dir := Vector2.ZERO
	if Input.is_physical_key_pressed(KEY_A):
		dir.x -= 1
	if Input.is_physical_key_pressed(KEY_D):
		dir.x += 1
	if Input.is_physical_key_pressed(KEY_W):
		dir.y -= 1
	if Input.is_physical_key_pressed(KEY_S):
		dir.y += 1
	player.velocity = dir.normalized() * player_speed
	player.move_and_slide()

	# Tile under player
	var tm = manifest.get("tilemap", {})
	if tm.has("grid"):
		var grid: Array = tm["grid"]
		var tx := int(player.global_position.x / TILE)
		var ty := int(player.global_position.y / TILE)
		if ty >= 0 and ty < grid.size():
			var row: Array = grid[ty]
			if tx >= 0 and tx < row.size():
				var tile_id := str(row[tx])
				var defs = tm.get("tile_defs", {})
				if bool(defs.get(tile_id, {}).get("spawn_enemy", false)):
					if randf() < 0.9 and _now_ms() > float(_encounter_cd_ms):
						_encounter_cd_ms = _now_ms() + 3000.0
						_start_battle(false)
						return
				if tile_id == "gym":
					_start_battle(true)
					return


func _start_battle(boss: bool) -> void:
	in_battle = true
	is_boss_fight = boss
	var base_hp := int(manifest.get("game_config", {}).get("enemy", {}).get("base_hp", 60))
	enemy_max_hp = base_hp * (3 if boss else 1)
	enemy_hp = enemy_max_hp
	selected = 0

	var dim := ColorRect.new()
	dim.name = "BattleBG"
	dim.color = Color(0.04, 0.04, 0.1)
	dim.size = Vector2(480, 320)
	dim.z_index = 50
	hud_layer.add_child(dim)

	var foe := ColorRect.new()
	foe.name = "Foe"
	foe.color = palette["accent"] if not boss else Color(0.7, 0.2, 0.2)
	foe.position = Vector2(300, 90)
	foe.size = Vector2(48, 48) if boss else Vector2(32, 32)
	foe.z_index = 51
	hud_layer.add_child(foe)

	battle_log = Label.new()
	battle_log.name = "BattleLog"
	battle_log.text = "GYM LEADER BATTLE!" if boss else "A WILD FOE APPEARS!"
	battle_log.position = Vector2(120, 200)
	battle_log.add_theme_font_size_override("font_size", 11)
	battle_log.z_index = 52
	hud_layer.add_child(battle_log)

	for i in range(menu_actions.size()):
		var l := Label.new()
		l.text = menu_actions[i]
		l.position = Vector2(280 + (i % 2) * 90, 230 + int(i / 2.0) * 22)
		l.add_theme_font_size_override("font_size", 11)
		l.z_index = 52
		hud_layer.add_child(l)
		battle_menu.append(l)
	_update_menu()


func _update_menu() -> void:
	for i in range(battle_menu.size()):
		battle_menu[i].text = ("> " if i == selected else "  ") + menu_actions[i]


func _battle_update(delta: float) -> void:
	if _pending_enemy:
		_enemy_timer -= delta
		if _enemy_timer <= 0.0:
			_pending_enemy = false
			_enemy_turn()
		return

	if Input.is_physical_key_pressed(KEY_LEFT) or Input.is_physical_key_pressed(KEY_A):
		selected = (selected + menu_actions.size() - 1) % menu_actions.size()
		_update_menu()
		return
	if Input.is_physical_key_pressed(KEY_RIGHT) or Input.is_physical_key_pressed(KEY_D):
		selected = (selected + 1) % menu_actions.size()
		_update_menu()
		return
	if Input.is_physical_key_pressed(KEY_SPACE) or Input.is_physical_key_pressed(KEY_ENTER):
		_player_action()


func _player_action() -> void:
	var bcfg = manifest.get("game_config", {}).get("battle", {})
	match menu_actions[selected]:
		"ATTACK":
			enemy_hp -= int(bcfg.get("base_attack", 20)) + randi() % 11 - 5
			_after_player()
		"MAGIC":
			if player_mp < 10:
				return
			player_mp -= 10
			enemy_hp -= int(bcfg.get("base_magic", 30))
			_after_player()
		"HEAL":
			if player_mp < 8:
				return
			player_mp -= 8
			player_hp = min(max_hp, player_hp + int(bcfg.get("base_heal", 25)))
			_after_player()
		"RUN":
			_end_battle(false)


func _after_player() -> void:
	hud_set("hp", "HP %d/%d" % [max(player_hp, 0), max_hp])
	if enemy_hp <= 0:
		score += 200
		battle_log.text = "FOE DEFEATED!"
		await get_tree().create_timer(1.2).timeout
		_end_battle(true)
		return
	battle_log.text = "FOE ATTACKS..."
	_pending_enemy = true
	_enemy_timer = 0.8


func _enemy_turn() -> void:
	var mult := 1.5 if is_boss_fight else 1.0
	var dmg := int(float(manifest.get("game_config", {}).get("enemy", {}).get("base_attack", 15)) * mult)
	player_hp -= dmg
	battle_log.text = "TOOK %d DAMAGE!" % dmg
	hud_set("hp", "HP %d/%d" % [max(player_hp, 0), max_hp])
	if player_hp <= 0:
		if is_boss_fight:
			# retry â€” heal a bit and stay in battle
			player_hp = int(max_hp * 0.6)
			battle_log.text = "DOWN... BUT NOT OUT! (RETRY)"
		else:
			trigger_game_over("DEFEAT...", Color.RED)


func _end_battle(won: bool) -> void:
	for child in hud_layer.get_children():
		if child.name in ["BattleBG", "Foe", "BattleLog"] or child in battle_menu:
			child.queue_free()
	battle_menu.clear()
	in_battle = false
	if won:
		encounters += 1
		player_mp = min(max_mp, player_mp + 5)
		if is_boss_fight:
			trigger_game_over("VICTORY! GYM BADGE EARNED! +1000", Color(0.3, 1.0, 0.3))
			score += 1000
		hud_set("enc", "WINS %d" % encounters)
"""

# â”€â”€ Exporter â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

GENRE_SCRIPTS = {
    "wave_shooter": GENRE_WAVE_SHOOTER,
    "top_down_action_rpg": GENRE_TOP_DOWN_RPG,
    "open_world_sandbox": GENRE_OPEN_WORLD,
    "side_scroll_platformer": GENRE_PLATFORMER,
    "turn_based_rpg": GENRE_TURN_BASED,
}


def _clear_color(manifest: dict) -> str:
    bg = (manifest.get("palette") or {}).get("background", "#0d0500")
    if isinstance(bg, str) and bg.startswith("#"):
        h = bg.lstrip("#")
        try:
            r, g, b = (int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
            return f"{r}, {g}, {b}, 1"
        except ValueError:
            pass
    return "0.05, 0.02, 0, 1"


def generate_godot_project(manifest: dict, demake_output_dir: str,
                           project_dir: str) -> str:
    """
    Emit a runnable Godot 4 project for the given manifest.

    manifest            â€” the demake manifest dict (tilemap, palette, assets)
    demake_output_dir   â€” backend outputs/{id}/ (source of sprite PNGs)
    project_dir         â€” where to write the project folder
    Returns the project_dir.
    """
    genre = manifest.get("template", "wave_shooter")
    if genre not in VALID_GENRES:
        genre = "wave_shooter"

    if os.path.isdir(project_dir):
        shutil.rmtree(project_dir)
    os.makedirs(os.path.join(project_dir, "scenes"), exist_ok=True)
    os.makedirs(os.path.join(project_dir, "scripts", "genres"), exist_ok=True)
    os.makedirs(os.path.join(project_dir, "assets", "sprites"), exist_ok=True)

    # â”€â”€ Copy sprites, rewrite manifest asset URLs to res:// paths â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    sprites = (manifest.get("assets") or {}).get("sprites") or {}
    for slot, url in list(sprites.items()):
        filename = os.path.basename(str(url))
        src = os.path.join(demake_output_dir, "sprites", filename)
        if not os.path.exists(src):
            src = os.path.join(demake_output_dir, filename)
        if os.path.exists(src):
            dst = os.path.join(project_dir, "assets", "sprites", filename)
            shutil.copyfile(src, dst)
            res_path = "res://assets/sprites/" + filename
            if slot.startswith("sprite_"):
                # slot key -> GDScript _slot_texture name
                sprites[slot] = res_path
                sprites.setdefault(slot.replace("sprite_", ""), res_path)
            else:
                sprites[slot] = res_path

    # â”€â”€ Write files â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    title = str(manifest.get("title", "DEMAKE")).replace('"', "'")
    with open(os.path.join(project_dir, "project.godot"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(PROJECT_GODOT_TMPL.format(
            title=title, clear_color=_clear_color(manifest)))

    with open(os.path.join(project_dir, "scenes", "main.tscn"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(MAIN_TSCN)

    with open(os.path.join(project_dir, "manifest.json"), "w",
              encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2)

    scripts_dir = os.path.join(project_dir, "scripts")
    with open(os.path.join(scripts_dir, "main.gd"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(MAIN_GD_TMPL.format(genre=genre))

    with open(os.path.join(scripts_dir, "base.gd"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(BASE_GD)

    with open(os.path.join(scripts_dir, "genres", f"{genre}.gd"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(GENRE_SCRIPTS[genre])

    print(f"[GodotExport] Project written: {project_dir} (genre={genre})")
    return project_dir


def zip_project(project_dir: str, zip_path: str) -> str:
    """Zip the generated project for download. Returns zip_path."""
    if os.path.exists(zip_path):
        os.remove(zip_path)
    parent = os.path.dirname(project_dir)
    folder = os.path.basename(project_dir)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, _dirs, files in os.walk(project_dir):
            for name in files:
                full = os.path.join(root, name)
                rel = os.path.relpath(full, parent)
                zf.write(full, arcname=rel)
    print(f"[GodotExport] Zipped: {zip_path} "
          f"({os.path.getsize(zip_path) / 1024:.0f} KB)")
    return zip_path


def find_godot_binary() -> str | None:
    for cand in GODOT_CANDIDATES:
        if os.path.exists(cand):
            return cand
    return None


def headless_validate(project_dir: str, frames: int = 120) -> dict:
    """
    Run the project headless for N frames to catch script errors.
    Returns { ok, output } â€” parse output for SCRIPT ERROR lines.
    """
    godot = find_godot_binary()
    if not godot:
        return {"ok": False, "output": "Godot binary not found"}
    import subprocess
    proc = subprocess.run(
        [godot, "--headless", "--path", project_dir,
         "--import", "--quit-after", str(frames)],
        capture_output=True, text=True, timeout=120,
    )
    out = (proc.stdout or "") + (proc.stderr or "")
    ok = "SCRIPT ERROR:" not in out and "Parse Error" not in out
    return {"ok": ok, "output": out}
